### ISSUE TITLE
GPU inference not working

### ISSUE THREAD

**Issue by averkij** [r2d4/rellm#1]
Hi, thanks for your work. 

When I'm trying to do generation on GPU I get the following error inside logits_processor.py in transformers (I've tried to place tensors on cuda inside compile_re).

```
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```

How to use rellm on gpu?

**Comment by r2d4** [comment]
ReLLM is only a wrapper around calling the huggingface transformers PreTrainedModel. It only does some work around filtering logits and calling the model.generate method.

Do your model.generate workout outside the complete_re call?
